name: tufly
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.9
  modal_progress_hud_nsn: ^0.3.0
  email_validator: ^2.1.17
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.6
  provider: ^6.0.4
  mpesa_flutter_plugin: ^1.6.1
  flutter_ticket_widget: ^0.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf